# graylog.yml
# Traefik dynamic/running config specified in static config

http:
  routers:
    graylog-router:
      entryPoints:
        - "https"
      rule: "Host(`abe-lab12.logfather.org`)"
      service: "graylog-web"
      tls: {}
  services:
    graylog-web:
      loadBalancer:
        servers:
          - url: "http://izrfyicsax7m6imkf-646e2dd343aad0153e4e3b54.labs.strigo.io:9000/" 
          - url: "http://izrfyicsax7m6imkf-646e2dd343aad0153e4e3b55.labs.strigo.io:9000/"
          - url: "http://izrfyicsax7m6imkf-646e419ea072e7d4bbe71be4.labs.strigo.io:9000/"
        healthCheck:
          path: /api/system/lbstatus

# Declare cert & key used by websecure entrypoint:
tls:
  certificates:
    - certFile: "/etc/traefik/certs/fullchain.pem"
      keyFile: "/etc/traefik/certs/privkey.pem"

tcp:
  routers:
    beats-router:
      entryPoints:
        - "beats"
      rule: "HostSNIRegexp(`{subdomain:[a-z]+}.logfather.org`)"
      service: "beats"
      tls: {}
    raw-router:
      entryPoints:
        - "raw"
      rule: "HostSNIRegexp(`{subdomain:[a-z]+}.logfather.org`)"
      service: "raw"
      tls: {}
  services:
    beats:
      loadBalancer:
        servers:
          - address: "localhost:5044"
#          - address: "localhost:5045"
#          - address: "localhost:5046"
    raw:
      loadBalancer:
        servers:
          - address: "localhost:5555"
#          - address: "localhost:5556"
#          - address: "localhost:5557"

udp:
  routers:
    syslog-router:
      entryPoints:
        - "syslog"
      service: "syslog"
  services:
    syslog:
      loadBalancer:
        servers:
          - address: "localhost:514"
#          - address: "localhost:1514"
#          - address: "localhost:11514"