# traefik.yml
# Main Traefik static/startup config


# Logging options:
log:
  filePath: "/var/log/traefik/server.log"
  level: DEBUG

accessLog:
  filePath: "/var/log/traefik/access.log"

# Enable API (optional):
# Enabling the API in production is not recommended, because it will expose all configuration elements, including sensitive data.
api:
  dashboard: true                             # Enable the dashboard
  insecure: true

# Certificate Resolvers are responsible for retrieving certificates from an ACME server
# See https://doc.traefik.io/traefik/https/acme/#certificate-resolvers

# Entrypoints (listeners):
entryPoints:
  http:
    address: ":80"                            # Create the HTTP entrypoint on port 80
    http:
      redirections:                           # HTTPS redirection (80 to 443)
        entryPoint:
          to: "https"                         # The target element
          scheme: "https"                     # The redirection target scheme
  https:
    address: ":443"                           # Create the HTTPS entrypoint on port 443
    http:
      tls:
        domains:
          - main: "logfather.org"             # The target domains for TLS hostname verification
          #- sans: "logfather.org"            # Specify SANS DNS and/or IP's if necessary
  syslog:
    address: ":514/udp"
      forwardedHeaders:
      trustedIPs:
        - "172.16.0.0/12"                     # Add your IP's or subnets here where Graylog Inputs are listening
  beats:
    address: ":5044/tcp"
      forwardedHeaders:
      trustedIPs:
        - "172.16.0.0/12"                     # Add your IP's or subnets here where Graylog Inputs are listening
  raw:
    address: ":5555/tcp"
      forwardedHeaders:
      trustedIPs:
        - "172.16.0.0/12"                     # Add your IP's or subnets here where Graylog Inputs are listening

global:
  checknewversion: true                       # Periodically check if a new version has been released.
  sendanonymoususage: true                    # Periodically send anonymous usage statistics.

providers:
  file:
    filename: "/etc/traefik/config.yml"       # Link to the dynamic configuration
    watch: true                               # Watch for modifications
  providersThrottleDuration: 10               # Configuration reload frequency