admin@ip-172-31-1-137:/etc/traefik$ cat dynamic.toml 
# dynamic.toml
# Traefik dynamic/running config specified in static config


# Declare cert & key used by websecure entrypoint:
[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/home/admin/.class/certs/cert.pem"
      keyFile = "/home/admin/.class/certs/privkey.pem"


[http.routers]
  [[http.routers.graylog-web]]
    entryPoints = ["websecure"]
    # Need to set this to whatever the user is going to put in the URL, which I think is the *.logfather.org DNS record.
    # Is there an env var that will contain this?
    rule = "Host(`abe-lab12.logfather.org`)"
    service = "graylog-web"


[http.services]
  [http.services.graylog-web.loadBalancer]
    [http.services.graylog-web.loadBalancer.healthCheck]
      path = "/api/system/lbstatus"
    
    [[http.services.graylog-web.loadBalancer.servers]]
      url = "http://izrfyicsax7m6imkf-646e2dd343aad0153e4e3b54.labs.strigo.io:9000/"  # *.strigo.io addresses should be fine here

    [[http.services.graylog-web.loadBalancer.servers]]
      url = "http://izrfyicsax7m6imkf-646e2dd343aad0153e4e3b55.labs.strigo.io:9000/"

    [[http.services.graylog-web.loadBalancer.servers]]
      url = "http://izrfyicsax7m6imkf-646e419ea072e7d4bbe71be4.labs.strigo.io:9000/"


[tcp.routers]
  [tcp.routers.beats]
    entryPoints = ["beats"]
    rule = "HostSNIRegexp(`{subdomain:[a-z]+}.logfather.org`)"
    service = "beats"

  [tcp.routers.raw]
    entryPoints = ["raw"]
    rule = "HostSNIRegexp(`{subdomain:[a-z]+}.logfather.org`)"
    service = "raw"


[tcp.services]
  [tcp.services.beats.loadBalancer]
    # These need to be IP addresses, so there needs to be an env var set
    # that contains IP addresses for each clustered node. A simple
    # nslookup against the strigo.io hostname in the launch script should work
    [[tcp.services.beats.loadBalancer.servers]]
      address = "172.31.44.215:5044"

    [[tcp.services.beats.loadBalancer.servers]]
      address = "172.31.36.55:5044"

    [[tcp.services.beats.loadBalancer.servers]]
      address = "172.31.45.24:5044"

  [tcp.services.raw.loadBalancer]
    [[tcp.services.raw.loadBalancer.servers]]
      address = "172.31.44.215:5555"

    [[tcp.services.raw.loadBalancer.servers]]
      address = "172.31.45.24:5555"

    [[tcp.services.raw.loadBalancer.servers]]
      address = "172.31.36.55:5555"


[udp.routers]
  [udp.routers.syslog]
    entryPoints = ["syslog"]
    service = "syslog"


[udp.services]
  [udp.services.syslog]
    [[udp.services.syslog.loadBalancer.servers]]
      address = "172.31.45.24:514"  # *.strigo.io addresses should be fine here

    [[udp.services.syslog.loadBalancer.servers]]
      address = "172.31.44.215:514"

    [[udp.services.syslog.loadBalancer.servers]]
      address = "172.31.36.55:514"