# dynamic.toml
# Traefik dynamic/running config specified in static config


# Declare cert & key used by websecure entrypoint:
[[tls.certificates]]
  certFile = "/etc/traefik/certs/fullchain.pem"
  keyFile = "/etc/traefik/certs/privkey.pem"

[http.routers]
  [[http.routers.graylog-router]]
    entryPoints = ["https"]
    rule = "Host(`{{env publicdns}}`)"
    service = "graylog-web"
    [http.routers.graylog-router.tls]
[http.services]
  [http.services.graylog-web.loadBalancer]                      # These addresses need only to be resolvable/routable from Traefik host
    [[http.services.graylog-web.loadBalancer.servers]]
      url = "http://{{env STRIGO_RESOURCE_0_DNS}}:9000/"
    [[http.services.graylog-web.loadBalancer.servers]]
      url = "http://{{env STRIGO_RESOURCE_1_DNS}}:9000/"
    [[http.services.graylog-web.loadBalancer.servers]]
      url = "http://{{env STRIGO_RESOURCE_2_DNS}}:9000/"
    [http.services.graylog-web.loadBalancer.healthCheck]
      path = "/api/system/lbstatus"                             # Graylog API endpoint to query for LB status

[tcp.routers]
  [tcp.routers.beats-router]
    entryPoints = ["beats"]
    rule = "HostSNIRegexp(`{subdomain:[a-z]+}.logfather.org`)"
    service = "beats"
    [tcp.routers.beats-router.tls]
  [tcp.routers.raw-router]
    entryPoints = ["raw"]
    rule = "HostSNIRegexp(`{subdomain:[a-z]+}.logfather.org`)"
    service = "raw"
    [tcp.routers.raw-router.tls]
[tcp.services]
  [tcp.services.beats-service.loadBalancer]                     # Due to the nature of TCP/UDP, these values need to be IP addresses and cannot be hostnames
    [[tcp.services.beats-service.loadBalancer.servers]]
      address = "{{env STRIGO_RESOURCE_0_IP}}:5044"
    [[tcp.services.beats-service.loadBalancer.servers]]
      address = "{{env STRIGO_RESOURCE_1_IP}}:5044"
    [[tcp.services.beats-service.loadBalancer.servers]]
      address = "{{env STRIGO_RESOURCE_2_IP}}:5044"
  [tcp.services.raw-service.loadBalancer]                       # Due to the nature of TCP/UDP, these values need to be IP addresses and cannot be hostnames
    [[tcp.services.raw-service.loadBalancer.servers]]
      address = "{{env STRIGO_RESOURCE_0_IP}}:5555"
    [[tcp.services.raw-service.loadBalancer.servers]]
      address = "{{env STRIGO_RESOURCE_1_IP}}:5555"
    [[tcp.services.raw-service.loadBalancer.servers]]
      address = "{{env STRIGO_RESOURCE_2_IP}}:5555"

[udp.routers]
  [udp.routers.syslog-router]
    entryPoints = ["syslog"]
    service = "syslog-service"
[udp.services]
  [udp.services.syslog-service]
    [[udp.services.syslog-service.loadBalancer.servers]]
      address = "{{env STRIGO_RESOURCE_0_IP}}:514"              # Due to the nature of TCP/UDP, these values need to be IP addresses and cannot be hostnames
    [[udp.services.syslog-service.loadBalancer.servers]]
      address = "{{env STRIGO_RESOURCE_1_IP}}:514"
    [[udp.services.syslog-service.loadBalancer.servers]]
      address = "{{env STRIGO_RESOURCE_2_IP}}:514"
