# traefik.toml
# Main Traefik static/startup config


# Specify logging options:
[log]
  level = "DEBUG"
  format = "json"
  filepath = "/var/log/traefik/traefik.log"


[entryPoints]

  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"

  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http.tls]
      [[entryPoints.websecure.http.tls.domains]]
        main = "{{env publicdns}}"  # Unsure if wildcard in CN will work. If not, can just put whatever we want here bc the SAN is the only thing apps care about these days
        sans = ["{{env publicdns}}"]

  [entryPoints.syslog]
    address = ":514/udp"

  [entryPoints.beats]
    address = ":5044"  

  [entryPoints.raw]
    address = ":5000"


[providers] 
  [providers.file]
    watch = true
    filename = "/home/admin/.class/CLUSTER/.configs/dynamic.toml"