# Listen on all addresses available, port 1337
listenAddressSingleHTTPFrontend: 0.0.0.0:1337 

# Choose from INFO (default), WARN and DEBUG
logLevel: "DEBUG"
showFooter: false
showNewVersions: false
themeName: graylog-theme

actions:   
- title: windowsfirewall-sample
  shell: pwsh -c 'Send-logs windowsfirewall-sample'
  icon: "&#128293"
  timeout: 1200

- title: Windows Firewall Logs
  shell: pwsh -c 'Send-logs windowsfirewall'
  icon: "&#128293"
  timeout: 1200