{
 "title": "Graylog-Server",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Node Exp. Job",
    "query": {
     "query": "label_values(node_uname_info{instance!~\"192.168.0.106:9100|graylog-indexer.drew.local:9100|192.168.0.1:9100\"}, job)"
    }
   },
   {
    "name": "node",
    "label": "Node Exp. Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "extract_hostname_only",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "glinstance",
    "label": "Graylog Instance",
    "query": {
     "query": "label_values(gl_system_job_manager_executor_thread{instance=~\"graylog:9833\"},instance)"
    }
   },
   {
    "name": "real_node",
    "label": "Node:",
    "query": {
     "query": "label_values(gl_system_job_manager_executor_thread{instance=\"$glinstance\"}, node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node Exporter Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  { "title": "Summary Guages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Load 5",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load5{instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A/$B)*100\n", "type": "math" }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "(($Total-$B)/$Total)*100", "type": "math" }
   ]
  },
  {
   "title": "Process Buffer",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gl_buffer_usage{node=\"$real_node\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$node\"}",
     "legendFormat": "load1"
    },
    {
     "expr": "node_load5{instance=\"$node\"}",
     "legendFormat": "load5"
    },
    {
     "expr": "node_load15{instance=\"$node\"}",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "Resource Waiting Seconds",
   "type": "timeseries",
   "description": "Total time in seconds that processes have waited for CPU time",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "delta(node_pressure_cpu_waiting_seconds_total{job=\"$job\"}[30s])",
     "legendFormat": "CPU Waiting"
    },
    {
     "expr": "delta(node_pressure_io_stalled_seconds_total{job=\"$job\"}[30s])",
     "legendFormat": "IO Stalled"
    },
    {
     "expr": "delta(node_pressure_io_waiting_seconds_total{job=\"$job\"}[30s])",
     "legendFormat": "IO Waiting"
    },
    {
     "expr": "delta(node_pressure_memory_stalled_seconds_total{job=\"$job\"}[30s])",
     "legendFormat": "Mem Stalled"
    },
    {
     "expr": "delta(node_pressure_memory_waiting_seconds_total{job=\"$job\"}[30s])",
     "legendFormat": "Mem Waiting"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_AnonPages_bytes{instance=\"$node\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expression": "$Total-$B", "type": "math" },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\", instance=\"$node\"}",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Throughput and Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Message Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "delta(gl_buffer_incoming_messages_total{node=\"$real_node\", type=\"input\"}[1m])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "delta(gl_buffer_incoming_messages_total{node=\"$real_node\", type=\"process\"}[1m])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "delta(gl_buffer_incoming_messages_total{node=\"$real_node\", type=\"output\"}[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Traffic (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(gl_traffic_input{node=\"$real_node\"}[$__rate_interval])",
     "legendFormat": "Input"
    },
    {
     "expr": "increase(gl_traffic_output{node=\"$real_node\"}[$__rate_interval])",
     "legendFormat": "Output"
    },
    {
     "expr": "increase(gl_traffic_decoded{node=\"$real_node\"}[$__rate_interval])",
     "legendFormat": "Decoded"
    }
   ]
  },
  {
   "title": "Throughput (1sec rate)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "gl_throughput_input_1_sec_rate{node=\"$real_node\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "gl_throughput_output_1_sec_rate{node=\"$real_node\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Throughput Difference",
   "type": "timeseries",
   "description": "Input is greater than output",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 31 },
   "targets": [
    { "expression": "$B-$A", "type": "math" }
   ]
  },
  {
   "title": "Max Input",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "gl_throughput_input_1_sec_rate{node=\"$real_node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Output",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "gl_throughput_output_1_sec_rate{node=\"$real_node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Difference",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expression": "$B-$A", "type": "math" }
   ]
  },
  { "title": "Buffers and Journal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Buffer Process Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gl_buffer_process_time{node=\"$real_node\"}",
     "legendFormat": "{{type}} {{quantile}}"
    }
   ]
  },
  {
   "title": "gl_buffer_usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gl_buffer_usage{node=\"$real_node\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "gl_buffer_incoming_messages_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gl_buffer_incoming_messages_total{node=\"$real_node\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "gl_journal_entries_uncommitted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gl_journal_entries_uncommitted{node=\"$real_node\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Journal Append/Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gl_journal_append_1_sec_rate{node=\"$real_node\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "gl_journal_read_1_sec_rate{node=\"$real_node\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Journal Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gl_journal_utilization_ratio{node=\"$real_node\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gl_jvm_memory_total_max{node=\"$real_node\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "gl_jvm_memory_total_used{node=\"$real_node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "gl_jvm_memory_total_committed{node=\"$real_node\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gl_jvm_memory_heap_init{node=\"$real_node\"}",
     "legendFormat": "Init"
    },
    {
     "expr": "gl_jvm_memory_heap_committed{node=\"$real_node\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "gl_jvm_memory_heap_max{node=\"$real_node\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "gl_jvm_memory_heap_used{node=\"$real_node\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gl_jvm_memory_non_heap_init{node=\"$real_node\"}",
     "legendFormat": "Init"
    },
    {
     "expr": "gl_jvm_memory_non_heap_committed{node=\"$real_node\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "gl_jvm_memory_non_heap_used{node=\"$real_node\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "JVM Committed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gl_jvm_memory_pools_G1_Survivor_Space_committed{node=\"$real_node\"}",
     "legendFormat": "G1 Survivor Space"
    },
    {
     "expr": "gl_jvm_memory_pools_G1_Eden_Space_committed{node=\"$real_node\"}",
     "legendFormat": "G1 Eden Space"
    },
    {
     "expr": "gl_jvm_memory_pools_Compressed_Class_Space_committed{node=\"$real_node\"}",
     "legendFormat": "Compressed Class Space"
    },
    {
     "expr": "gl_jvm_memory_pools_G1_Old_Gen_committed{node=\"$real_node\"}",
     "legendFormat": "G1 Old Gen"
    },
    {
     "expr": "gl_jvm_memory_pools_Metaspace_committed{node=\"$real_node\"}",
     "legendFormat": "Metaspace"
    }
   ]
  },
  {
   "title": "JVM Used after GC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gl_jvm_memory_pools_G1_Old_Gen_used_after_gc{node=\"$real_node\"}",
     "legendFormat": "G1 Old Gen"
    },
    {
     "expr": "gl_jvm_memory_pools_G1_Survivor_Space_used_after_gc{node=\"$real_node\"}",
     "legendFormat": "G1 Survivor"
    },
    {
     "expr": "gl_jvm_memory_pools_G1_Eden_Space_used_after_gc{node=\"$real_node\"}",
     "legendFormat": "G1 Eden"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "idelta(gl_jvm_gc_G1_Young_Generation_time{node=\"$real_node\"}[5m])",
     "legendFormat": "GC Young Gen Time"
    },
    {
     "expr": "idelta(gl_jvm_gc_G1_Old_Generation_time{node=\"$real_node\"}[5m])",
     "legendFormat": "GC Old Gen Time"
    }
   ]
  },
  {
   "title": "JVM Memory Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gl_jvm_memory_heap_usage{node=\"$real_node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "G1 Old Gen Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gl_jvm_memory_pools_G1_Old_Gen_usage{node=\"$real_node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "G1 Survivor Space Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gl_jvm_memory_pools_G1_Survivor_Space_usage{node=\"$real_node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "G1 Eden Space Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gl_jvm_memory_pools_G1_Eden_Space_usage{node=\"$real_node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compressed Class Space Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gl_jvm_memory_pools_Compressed_Class_Space_usage{node=\"$real_node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metaspace Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gl_jvm_memory_pools_Metaspace_usage{node=\"$real_node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Memory Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gl_jvm_memory_heap_usage{node=\"$real_node\"}",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "G1 Old Gen Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gl_jvm_memory_pools_G1_Old_Gen_usage{node=\"$real_node\"}",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "G1 Survivor Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gl_jvm_memory_pools_G1_Survivor_Space_usage{node=\"$real_node\"}",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "G1 Eden Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gl_jvm_memory_pools_G1_Eden_Space_usage{node=\"$real_node\"}",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Compressed Class Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gl_jvm_memory_pools_Compressed_Class_Space_usage{node=\"$real_node\"}",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Metaspace Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gl_jvm_memory_pools_Metaspace_usage{node=\"$real_node\"}",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "JVM G1 Old Gen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gl_jvm_memory_pools_G1_Old_Gen_init{node=\"$real_node\"}",
     "legendFormat": "Init"
    },
    {
     "expr": "gl_jvm_memory_pools_G1_Old_Gen_used_after_gc{node=\"$real_node\"}",
     "legendFormat": "Used After GC"
    },
    {
     "expr": "gl_jvm_memory_pools_G1_Old_Gen_used{node=\"$real_node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "gl_jvm_memory_pools_G1_Old_Gen_committed{node=\"$real_node\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "gl_jvm_memory_pools_G1_Old_Gen_max{node=\"$real_node\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "G1 Survivor Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gl_jvm_memory_pools_G1_Survivor_Space_committed{node=\"$real_node\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "gl_jvm_memory_pools_G1_Survivor_Space_used_after_gc{node=\"$real_node\"}",
     "legendFormat": "After GC"
    }
   ]
  },
  {
   "title": "G1 Eden Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gl_jvm_memory_pools_G1_Eden_Space_init{node=\"$real_node\"}",
     "legendFormat": "Init"
    },
    {
     "expr": "gl_jvm_memory_pools_G1_Eden_Space_committed{node=\"$real_node\"}",
     "legendFormat": "Commited"
    }
   ]
  },
  {
   "title": "Compressed Class",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gl_jvm_memory_pools_Compressed_Class_Space_used{node=\"$real_node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "gl_jvm_memory_pools_Compressed_Class_Space_committed{node=\"$real_node\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gl_jvm_memory_pools_Metaspace_committed{node=\"$real_node\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "gl_jvm_memory_pools_Metaspace_used{node=\"$real_node\"}",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "HTTP Worker Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gl_jersey_http_worker_duration{node=\"$real_node\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "HTTP Worker Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "expr": "gl_jersey_http_worker_executor_thread{type=\"idle\", quantile=\"0.999\", node=\"$real_node\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "gl_jersey_http_worker_executor_thread{type=\"running\", node=\"$real_node\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Lookup Table Totals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "rate(gl_lookup_table_requests_count{node=\"$real_node\"}[$__rate_interval])",
     "legendFormat": "{{lookup_table}}"
    }
   ]
  },
  {
   "title": "Lookup Table Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "gl_lookup_table_requests{node=\"$real_node\", quantile=\"0.99\"}",
     "legendFormat": "{{lookup_table}}"
    }
   ]
  },
  {
   "title": "Pipeline Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gl_pipeline_interpreter_execution_time{instance=\"$glinstance\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Pipeline Totals",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 131 },
   "targets": [
    {
     "expr": "rate(gl_pipeline_total{node=\"$real_node\", type=\"executed\"}[$__rate_interval])",
     "legendFormat": "{{pipeline}}"
    }
   ]
  },
  {
   "title": "Pipeline Rule Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 140 },
   "targets": [
    {
     "expr": "rate(gl_pipeline_rule_total{type=\"matched\", node=\"$real_node\"}[$__rate_interval])",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "Pipeline Rule Execution Duration",
   "type": "timeseries",
   "description": "TURN ON pipeline rule debug metrics!",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gl_pipeline_rule_stage_number{node=\"$real_node\", type=\"duration\", quantile=\"0.999\"}",
     "legendFormat": "{{rule}} {{stage_number}}"
    }
   ]
  },
  {
   "title": "Pipeline Rule Execution Duration",
   "type": "timeseries",
   "description": "TURN ON pipeline rule debug metrics!",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "gl_pipeline_rule_stage_number{node=\"$real_node\", type=\"duration\", quantile=\"0.999\", rule!~\"62a75e58a400bf11a5708624\"}",
     "legendFormat": "{{rule}} {{stage_number}}"
    }
   ]
  }
 ]
}