# Listen on all addresses available, port 1337
listenAddressSingleHTTPFrontend: 0.0.0.0:1337 



# Choose from INFO (default), WARN and DEBUG
logLevel: "DEBUG"
showFooter: false
showNewVersions: false
themeName: graylog-theme

actions:

- title: Mac Firewall Logs GELF
  shell: cat /etc/graylog/log_data/004-mf.log | ncat -w 1 localhost 5080
  icon: backup
  timeout: 900 

- title: Windows Firewall Logs
  shell: cat /etc/graylog/log_data/001-wf.log | ncat -w 1 localhost 5140
  icon: backup
  timeout: 900

- title: Mac Firewall Logs
  shell: cat /etc/graylog/log_data/004-mf.log | ncat -w 1 localhost 5050
  icon: backup
  timeout: 900

- title: Unrealistcally Large Log 1
  shell: cat /etc/graylog/log_data/600field1.log | ncat -w 1 localhost 5555
  icon: backup
  timeout: 900

- title: Unrealistcally Large Log 2
  shell: cat /etc/graylog/log_data/600filed2.log | ncat -w 1 localhost 5555
  icon: backup
  timeout: 900