# Listen on all addresses available, port 1337
listenAddressSingleHTTPFrontend: 0.0.0.0:1337 



# Choose from INFO (default), WARN and DEBUG
logLevel: "DEBUG"
showFooter: false
showNewVersions: false
themeName: graylog-theme



actions:   
- title: Windows Firewall Logs
  shell: cat /etc/graylog/log_data/001-wf.log | ncat -w 1 localhost 5140
  icon: backup
  timeout: 900

- title: Open/PFSense Firewall Logs
  shell: cat /etc/graylog/log_data/002-ofw.log | ncat -w 1 localhost 5140
  icon: backup
  timeout: 900

- title: PiHole Firewall Logs
  shell: cat /etc/graylog/log_data/004-phe.log | ncat -w 1 localhost 5555
  icon: backup
  timeout: 900