# Listen on all addresses available, port 1337
listenAddressSingleHTTPFrontend: 0.0.0.0:1337 

# Choose from INFO (default), WARN and DEBUG
logLevel: "DEBUG"
showFooter: false
showNewVersions: false
themeName: graylog-theme

actions:
- title: Demo Log
  shell: pwsh -c 'send-logs demo'
  icon: backup
  timeout: 900

- title: Dashboard Logs
  icon: "&#128269"
  shell: pwsh -c 'send-logs Dashboards'
  timeout: 1200

- title: Log Playback On
  shell: systemctl start gl-log-replay
  icon: "&#9654;&#65039;"
  timeout: 1200

- title: Log Playback Off
  shell: systemctl stop gl-log-replay
  icon: "&#9209;&#65039"
  timeout: 1200

- title: Windows Events
  shell: python3 /root/powershell/Data/simulate_windows_events.py --host localhost --port 12201
  icon: "&#128293"
  timeout: 1200

- title: Windows Firewall Logs
  shell: pwsh -c 'Send-logs windowsfirewall'
  icon: "&#128293"
  timeout: 1200

- title: Mac Firewall Logs
  shell: pwsh -c 'Send-logs macfirewall'
  icon: "&#127879"
  timeout: 1200
