# Listen on all addresses available, port 1337
listenAddressSingleHTTPFrontend: 0.0.0.0:1337 

# Choose from INFO (default), WARN and DEBUG
logLevel: "DEBUG"
showFooter: false
showNewVersions: false
themeName: graylog-theme

actions:
  - title: Demo Log - tcp/12201
    shell: pwsh -c 'send-logs demo'
    icon: backup
    timeout: 900

  - title: Lab Firewall Logs - tcp/12201
    shell: pwsh -c 'Send-logs pipeline-intro'
    icon: "&#128163"
    timeout: 1200

  - title: Windows Firewall Sample - udp/1500
    shell: pwsh -c 'Send-logs windowsfirewall-sample'
    icon: "&#128293"
    timeout: 1200

  - title: Windows Firewall Logs - udp/1500
    shell: pwsh -c 'Send-logs windowsfirewall'
    icon: "&#128293"
    timeout: 1200

  - title: Geolocation Test - tcp/12201
    shell: echo '{"version":1.1,"source_ip":"209.85.200.104","host":"graylog","short_message":"source ip test"}' | tr '\n' '\0' | nc -q0 localhost 12201
    icon: "&#127760"
    timeout: 1200

  - title: PFSense Logs - tcp/1515
    shell: cat /etc/graylog/log_data/firewall.log | sed "s/datetime/$(date +"%Y-%m-%dT%H:%M:%S%:z")/g" | nc -w 1 localhost 1515
    icon: '<img src = "https://raw.githubusercontent.com/Graylog2/graylog-training-data/main/6441615622c8f6a4e5a2c29c/images/pfsense-logo.png" width = "48px"/>'
    timeout: 900

  - title: PFSense Logs - udp/2514
    shell: cat /etc/graylog/log_data/firewall.log | sed "s/datetime/$(date +"%Y-%m-%dT%H:%M:%S%:z")/g" |  nc -uCw 1 127.0.0.1 2514
    icon: '<img src = "https://raw.githubusercontent.com/Graylog2/graylog-training-data/main/6441615622c8f6a4e5a2c29c/images/pfsense-logo.png" width = "48px"/>'
    timeout: 900

  - title: KVP Firewall Logs - tcp/1514
    shell: cat /etc/graylog/log_data/kvp.log | nc -w1 localhost 1514
    icon: "&#127879"
    timeout: 1200

  - title: KVP Firewall Logs - udp/2514
    shell: cat /etc/graylog/log_data/kvp.log | nc -uCw 1 localhost 2514
    icon: "&#127879"
    timeout: 1200

  - title: Day 3 Lab
    shell: cat /etc/graylog/log_data/bd-day3.log | nc -w1 localhost 5514
    icon: "&#127879"
    timeout: 1200