# Listen on all addresses available, port 1337
listenAddressSingleHTTPFrontend: 0.0.0.0:1337 

# Choose from INFO (default), WARN and DEBUG
logLevel: "DEBUG"
showFooter: false
showNewVersions: false

actions:   
- title: PFSense Logs
  shell: cat /etc/graylog/log_data/firewall.log | ncat -w 1 localhost 1514
  icon: backup
  timeout: 900

- title: We Book
  shell: while read x; do echo $x"\0" | ncat localhost 12201 -w200ms; done < /etc/graylog/log_data/we_book.log
  icon: "&#128218"
  timeout: 900
   
- title: Poetic Regex
  shell: while read x; do echo $x"\0" | ncat localhost 12201 -w50ms; done < /etc/graylog/log_data/nasty.log
  icon: "&#128513"
  timeout: 900