# Listen on all addresses available, port 1337
listenAddressSingleHTTPFrontend: 0.0.0.0:1337 

# Choose from INFO (default), WARN and DEBUG
logLevel: "DEBUG"
showFooter: false
showNewVersions: false
themeName: graylog-theme

actions:
- title: Demo Log
  shell: pwsh -c 'send-logs demo'
  icon: backup
  timeout: 900

- title: Dashboard Logs
  icon: "&#128269"
  shell: pwsh -c 'send-logs Dashboards'
  timeout: 1200

- title: Log Playback On
  shell: systemctl start gl-log-replay
  icon: "&#9654;&#65039;"
  timeout: 1200

- title: Log Playback Off
  shell: systemctl stop gl-log-replay
  icon: "&#9209;&#65039"
  timeout: 1200